name: Deploy gh-pages

on:
  push:
    branches:
      - flutter-portfolio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Usando v3 ao invés de v2, pois v3 tem melhorias

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'  # Certifique-se de especificar a versão do Flutter que você está utilizando

    - name: Build Flutter Web with CanvasKit
      run: flutter build web --web-renderer canvaskit --base-href=/Portfolio/

    - name: Deploy to GitHub Pages
      uses: bluefireteam/flutter-gh-pages@v7
      with:
        baseHref: /Portfolio/
